
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: albumgenie
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend-albumgenie
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/albumgenie
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    
  frontend:
    build:
      context: ./frontend
    container_name: frontend-albumgenie
    ports:
      - "80:80"
    depends_on:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@albumgenie.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-data: